name: Frontend CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          npm run test
  trigger-cd:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CD
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT  }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/TrefflyTeam/frontend/actions/workflows/cd.yml/dispatches?ref=develop \
          -d '{"ref":"develop"}'
